### ISSUE TITLE
[YBL]Final submission

### ISSUE THREAD

**Issue by devtrail42** [klaytn-hackathon/YBL#1]
- Youtube link : 
https://www.youtube.com/watch?v=aUh57mAp25s
 
-Final Project Paper :
[Final Project Paper.pdf](https://github.com/klaytn-hackathon/YBL/files/3241532/Final.Project.Paper.pdf)

-Contract address deployed on Baobab : 
Most recent address :
0x66cb1a3bB215fD647Ed62962e12787A30d33740b

Addresses deployed before :
0x186DfaBB3B936a428C98A70A79Bc649Fdbb567E9

0xbc4EE5de2D556e4f3E7589f591b714089C0D5100

0x1aDE6A85688E553882b1252541f5455021AF4371

**Comment by Klaytnhackathon** [comment]
Thanks for the final subsmission. First of all, we really appreciate your passion and effort you’ve been putting in this hackathon. We value your time and effort, and to appreciate it fully, we will proceed the judging process fairly with professional judges.

Finger crossed for winning the prize! And we will keep you updated through the hackathon website. Don’t hesitate to contact us either through Telegram or email.

Thank you again, and we will keep you updated!

**Comment by devtrail42** [comment]
안녕하세요!
이번에 클레이튼 해커톤에 참여한 YBL팀의 팀장
강병헌이라고 합니다.

다름이 아니라 이 확인메일이 오기 8분전에
git 이슈에 저희 결과물이 업로드 되지 않았다는
내용의 메일이 왔었습니다.
혹시 제출물이 확인되지 않았는데 이 확인 메일이 도착한건
아닐까 궁금해서 답신 보냅니다.

해커톤 진행하시느라 고생 많으셨습니다.
감사합니다.

2019년 6월 1일 (토) 오후 2:02, Klaytn Hackathon <notifications@github.com>님이 작성:

**Comment by Klaytnhackathon** [comment]
안녕하세요 @ariels1996, 현재 제출하신 결과물이 모두 잘 제출 된 것으로 확인됩니다. Github측에 오류가 있었던 건 아닌가 싶습니다. 감사합니다.

**Comment by devtrail42** [comment]
확인해주셔서 감사합니다.

좋은 하루 되시길 바라겠습니다 !!!

2019년 6월 1일 (토) 오후 3:24, Klaytn Hackathon <notifications@github.com>님이 작성:
